version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 421656561931.dkr.ecr.ap-northeast-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t dockerstore .
      - docker tag dockerstore:latest 421656561931.dkr.ecr.ap-northeast-1.amazonaws.com/dockerstore:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to Amazon ECR...
      - docker push 421656561931.dkr.ecr.ap-northeast-1.amazonaws.com/dockerstore:latest

