version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-1
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t my-image .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to Amazon ECR...
      - docker tag my-image:latest 421656561931.dkr.ecr.ap-northeast-1.amazonaws.com/my-image:latest
      - docker push 421656561931.dkr.ecr.ap-northeast-1.amazonaws.com/my-image:latest
